### ISSUE TITLE
Add ability to create resource groups

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-account-infrastructure-base#90]
### Description

Take a list of resource groups to create, set default to []

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@vburckhardt How would you propose to output the list of resource groups since stacks can only use string outputs?

**Comment by vburckhardt** [comment]
How about this.

Outputs:
- security-resource-group-name / security-resource-group-id
- audit-resource-group-name / id
- observability-resource-group-name / id
- management-resource-group-name / id
- workload-resource-group-name / id
- edge-resource-group-name / id
- devops-resource-group-name / id

Inputs:
- security-resource-group-name
- audit-resource-group-name
- observability-resource-group-name 
- management-resource-group-name
- workload-resource-group-name
- edge-resource-group-name
- devops-resource-group-name

Here is the caveat. In inputs the resource group can be the same. For instance, it should be possible to create one single resource group named "common-service-resource-group" for the security, audit, observability, devops services. This can be accomplished by using the same resource group name value as input of security-resource-group-name, audit-resource-group-name, observability-resource-group-name, devops-resource-group-name  . The logic should be smart enough to create only one single resource group in those cases.

This does give us the some flexibility in term of resource group topology while having a stable output interface for wiring.

**Comment by MatthewLemmond** [comment]
Created the PR for this here: https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/103, functionality works as described above where you can provide the same name for multiple resource groups and it will only create the number of resource groups needed, outputs will include the appropriate resource group name/id for that category so it doesn't matter if it's the same across the board all outputs will be included if that category has an input

Due to observability setup being optional, there is potentially a requirement to provide a resource group name for the observability category, but I have added a validation to check for this scenario and fail at plan time if it is not satisfied

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/releases/tag/v1.3.0
